import img1 from '../../assets/5373bdb8bf46a949e263c32e5f4154880fb081da.png'
import img2 from '../../assets/d60774e520db301441bf9c47a8b03447473d83d2.png'
import img3 from '../../assets/d38733bc95c7b74fae14454b186dd4cb422272e6.png'
import img4 from '../../assets/411ff4766e8e675b11f4af6ae34083103a95ec00.png'
import img5 from '../../assets/4fdfaf3f45ca3e76ea24a44e27f7804aabf34a12.png'
import almaMater from '../../assets/1186bb239a9a7ebde4b8be26b693ed2be4644dac.png'
import safetySmart from '../../assets/0da4047a925e7c5af57b083a5971a9c68c6628a3.jpg'
import dataprivacy from '../../assets/0da4047a925e7c5af57b083a5971a9c68c6628a3.jpg'
import awarnessSprint from '../../assets/1dd31dac9e356c1160e31c950b7780716e6e7d5d.png'
import innovationJam from '../../assets/0da4047a925e7c5af57b083a5971a9c68c6628a3.jpg'
import officeOlmypics from '../../assets/23aba9e2998a06376d9ecbc21fc6e302b30ca1c6.png'
import yearend from '../../assets/d29844c21cf8e4e13a79268f724706ddb5f883cf.png'
import newyearkickoff from '../../assets/27e42ede90ca830e0df76305541be0f3199f6da0.jpg'
import customerChallenge from '../../assets/388196778_4e64b692-3706-4c0d-b86b-0914459f8107 1.png'
import awarnessWeek from '../../assets/27e42ede90ca830e0df76305541be0f3199f6da0.jpg'
import cyberSecurtiy from '../../assets/d7b43ef75f494d3f2a7700377a82f16037ece4a2.png'
import diversityWeek from '../../assets/27e42ede90ca830e0df76305541be0f3199f6da0.jpg'
import salesSprint from '../../assets/1dd31dac9e356c1160e31c950b7780716e6e7d5d.png'
import hiddentalents from '../../assets/091ca18ad4cae01028d1012bab19f788c9c0a3ad.png'
export const EngageRythmCardData = [
    {
        name: "NGAGE RHYTHM",
        subTitle: "Culture Quest 1",
        category: "NGAGE Rhythm",
        img: img1,
        duration: "1 day",
        price: "US$699 (1-Day) | US$999 (3-Day)",
        season: "Year-round",
        theme: "",
        outcome: "Culture alignment",
        description: "Individuals explore company values through realistic workplace scenarios, puzzles, and trivia. The experience turns abstract values into everyday behaviours people can recognize and apply.",
        howToWin: "Top 3 with most points after completing all challenges. Bonus points for full completion.",
        activities: ["Trivia", "Wordify", "Mini-Quest", "Survey"],
        prizes: "Optional"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Wellness Recharge",
        category: "NGAGE Rhythm",
        img: img2,
        duration: "5 days",
        price: "US$1,499",
        season: "Year-round",
        theme: "",
        outcome: "Morale & balance",
        description: "A week-long wellness experience built around small, achievable daily actions. The focus is consistency, balance, and positive habits rather than competition.",
        howToWin: "Top 3 with the most points for daily participation.",
        activities: ["Social Quest", "Small Talk", "Trivia ", "Picture Puzzle"],
        prizes: "Included"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "World Cup Challenge",
        category: "NGAGE Rhythm",
        img:img3,
        duration: "5 days",
        price: "US$1,499",
        season: "Global Sports",
        theme: "Celebration, Team Spirit",
        outcome: "High participation",
        description: "A football-themed experience where teams predict match outcomes and complete fan challenges. It taps into real tournament excitement to drive natural participation.",
        howToWin: "Points for predictions, trivia accuracy, and bonus fan submissions.",
        activities: [ "Timed Trivia", "Survey", "Social Quest", "Picture Puzzle"],
        prizes: "Included"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Team Trivia League",
        category: "NGAGE Rhythm",
        img: img4,
        duration: "1 day",
        price: "US$699 (1-Day) | US$999 (3-Day)",
        season: "Summer",
        theme: "Fun, Competition",
        outcome: " Energy boost",
        description: "Fast-paced trivia rounds covering pop culture, general knowledge, or company topics. Designed for quick energy, friendly rivalry, and easy participation.",
        howToWin: "Highest cumulative team score wins.",
        activities: ["Timed Trivia", "Trivia", "Leaderboard"],
        prizes: "Optional"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Easter Scavenger Hunt",
        category: "NGAGE Rhythm",
        img: img5,
        duration: "3 days",
        price: "US$1,499",
        season: "Easter",
        theme: "Celebration, Play",
        outcome: "Shared fun",
        description: "A seasonal hunt where participants solve clues and discover hidden digital Easter eggs. The experience blends light problem-solving with playful surprises.",
        howToWin: "Collect all eggs and complete bonus challenges to score the most points.",
        activities: ["Treasure Hunt", "Scavenger Hunt", "Picture Puzzle", "Trivia", "Mini-Quest"],
        prizes: "Included"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Rep Your Alma Mater",
        category: "NGAGE Rhythm",
        img: almaMater,
        duration: "3 days",
        price: "US$999",
        season: "Easter, Summer",
        theme: "Identity, Belonging",
        outcome: "Connection",
        description: "Employees represent their schools or institutions through trivia and creative challenges. Friendly rivalry sparks conversation and shared stories across teams. ",
        howToWin: "Top 3 with the most points win.",
        activities: ["Trivia", "Social Quest", "Picture Puzzle", "Survey"],
        prizes: "Included"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Safety Smart",
        category: "NGAGE Rhythm",
        img: safetySmart,
        duration: "3 days",
        price: "US$999",
        season: "Year-round",
        theme: "Compliance, Learning",
        outcome: "Safety awareness",
        description: "Safety concepts are delivered through real-world scenarios and quick challenges. The experience reinforces correct decisions without feeling like formal training.",
        howToWin: "Points for correct responses and full completion.",
        activities: ["Trivia", "Timed Trivia", "Survey", "Mini-Quest"],
        prizes: "Optional"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Culture Quest 2",
        category: "NGAGE Rhythm",
        img: img1,
        duration: "3 days",
        price: "US$699 (1-Day) | US$999 (3-Day)",
        season: "Year-round",
        theme: "",
        outcome: "Culture alignment",
        description: "Teams explore company values through realistic workplace scenarios, puzzles, and trivia. The experience turns abstract values into everyday behaviours people can recognize and apply. Points for accuracy and completing all challenges. Bonus points for full completion.",
        howToWin: "Team with the highest score wins.",
        activities: ["Trivia", "Wordify", "Mini-Quest", "Treasure Hunt"],
        prizes: "Optional"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Data Privacy Challenge",
        category: "NGAGE Rhythm",
        img: dataprivacy,
        duration: "3 days",
        price: "US$999",
        season: "Year-round",
        theme: "Compliance",
        outcome: "Risk reduction, Increased Awareness",
        description: "Participants work through common data-privacy scenarios using short, focused challenges. The experience reinforces awareness in a practical, memorable way.",
        howToWin: "Complete all 7 levels and earn a Privacy badge.",
        activities: ["Quests•", "Timed Trivia", "Picture Puzzle", "Survey"],
        prizes: "Optional"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "AML Awareness Sprint",
        category: "NGAGE Rhythm",
        img: awarnessSprint,
        duration: "3 days",
        price: "US$999",
        season: "Year-round",
        theme: "Compliance",
        outcome: "Regulatory readiness, Awareness",
        description: "AML topics are broken into quick challenges designed to hold attention. The experience keeps learning light while reinforcing key concepts.",
        howToWin: "High accuracy across all scenarios.",
        activities: ["Trivia", "Timed Trivia", "Wordify", "Survey"],
        prizes: "Optional"
    },
    // {
    //     name: "NGAGE RHYTHM",
    //     subTitle: "Innovation Jam",
    //     category: "NGAGE Rhythm",
    //     img: innovationJam,
    //     duration: "5 days",
    //     price: "US$1,499",
    //     season: "Year-round",
    //     theme: "Innovation",
    //     outcome: "Idea generation",
    //     description: "Employees submit ideas, vote, and respond to creative prompts. The experience encourages participation and shared ownership of ideas.",
    //     howToWin: "Points for submissions, votes, and completion.",
    //     activities: ["Social Quest", "Survey", "Mini-Quest", "Picture Puzzle"],
    //     prizes: "Included"
    // },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Recognition Rally",
        category: "NGAGE Rhythm",
        img: officeOlmypics,
        duration: "3 days",
        price: "US$999",
        season: "Year-round",
        theme: "Appreciation",
        outcome: "Team morale boost, Motivation",
        description: "A peer-recognition experience focused on appreciation and positive behaviour. Teams celebrate wins and contributions together.",
        howToWin: "Points for giving and receiving recognition.",
        activities: ["Social Quest", "Survey", "Leaderboard"],
        prizes: "Included"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Year-End Wrap-Up",
        category: "NGAGE Rhythm",
        img: yearend,
        duration: "5 days",
        price: "US$1,499",
        season: "Autumn, Christmas",
        theme: "Celebration, Reflection",
        outcome: "Closure & appreciation",
        description: "A reflective end-of-year experience highlighting wins, milestones, and memories. It creates a shared sense of closure before the year ends.",
        howToWin: "Points for participation and trivia accuracy.",
        activities: ["Trivia", "Survey", "Social Quest", "Picture Puzzle"],
        prizes: "Included"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "New Year Kickoff Challenge",
        category: "NGAGE Rhythm",
        img: newyearkickoff,
        duration: "3 days",
        price: "US$1,499",
        season: "Seasonal (Q1)",
        theme: "Goals, Motivation",
        outcome: "Reinforce company goals",
        description: "Teams start the year with goal-setting and motivation challenges. The experience sets tone and focus for the months ahead.",
        howToWin: "Points for completing goal-based tasks.",
        activities: ["Survey", "Trivia", "Mini-Quest", "Wordify"],
        prizes: "Included"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Customer First Challenge",
        category: "NGAGE Rhythm",
        img: customerChallenge,
        duration: "3 days",
        price: "US$999",
        season: "Year-round",
        theme: "Service Excellence",
        outcome: "Customer mindset, Service Excellence",
        description: "Customer service scenarios are turned into short, interactive challenges. The experience reinforces empathy and service thinking.",
        howToWin: "Accuracy and completion.",
        activities: ["Trivia", "Timed Trivia", "Survey", "Mini-Quest"],
        prizes: "Optional"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "ESG Awareness Week",
        category: "NGAGE Rhythm",
        img: awarnessWeek,
        duration: "5 days",
        price: "US$1,499",
        season: "Year-round",
        theme: "Sustainability",
        outcome: "Strengthen ethical practices",
        description: "Participants explore ESG topics through simple, interactive challenges. The experience builds awareness without overwhelming detail. ",
        howToWin: "Top 3 with the  highest score wins.",
        activities: ["Quest", "Trivia", "Survey", "Picture Puzzle","Scavenger Hunt"],
        prizes: "Optional"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Cybersecurity Basics",
        category: "NGAGE Rhythm",
        img: cyberSecurtiy,
        duration: "3 days",
        price: "US$999",
        season: "Year-round",
        theme: "Compliance, Learning",
        outcome: "Cyber awareness",
        description: "Cybersecurity concepts are taught through practical scenarios and quizzes. The focus is everyday digital safety, not technical depth.",
        howToWin: "Get to level Speed and accuracy.",
        activities: ["Timed Trivia", "Card Collector", "Survey", "Picture Puzzle"],
        prizes: "Optional"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Diversity & Inclusion Week",
        category: "NGAGE Rhythm",
        img: diversityWeek,
        duration: "5 days",
        price: "US$1,499",
        season: "Year-round",
        theme: "Inclusion, Culture",
        outcome: "Awareness & empathy",
        description: "Participants engage with reflection prompts and learning challenges around inclusion. The experience encourages thoughtful participation and conversation.",
        howToWin: "Participation and completion.",
        activities: ["Survey", "Trivia", "Social Quest"],
        prizes: "Optional"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Sales Sprint",
        category: "NGAGE Rhythm",
        img: salesSprint,
        duration: "3 days",
        price: "US$999",
        season: "Year-round",
        theme: "Performance, Fun",
        outcome: "Motivation",
        description: "A short, competitive sprint focused on sales knowledge and activity. The experience adds energy without pressure.",
        howToWin: "Points for accuracy and task completion.",
        activities: ["Trivia", "Timed Trivia", "Mini-Quest", "Leaderboard"],
        prizes: "Included"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Hidden Talents Showcase",
        category: "NGAGE Rhythm",
        img: hiddentalents,
        duration: "1 days",
        price: "US$1,499",
        season: "Year-round",
        theme: "Fun, Culture",
        outcome: "Connection",
        description: "Employees share talents through photos or short videos. The experience highlights personality beyond job roles.",
        howToWin: "Points for submissions and peer engagement.",
        activities: ["Social Quest", "Picture Puzzle", "Survey"],
        prizes: "Included"
    },
    {
        name: "NGAGE RHYTHM",
        subTitle: "Office Olympics (Virtual Edition)",
        category: "NGAGE Rhythm",
        img:officeOlmypics,
        duration: "5 days",
        price: "US$1,499",
        season: "Year-round",
        theme: "Fun, Teamwork",
        outcome: "Participation boost",
        description: "A playful virtual Olympics with multiple mini-challenges. Players form teams based on countries in the Olympics and compete across events.",
        howToWin: "The team with the most points wins.",
        activities: ["Trivia", "Timed Trivia", "Social Quest", "Mini-Quest", "Leaderboard"],
        prizes: "Included"
    },

    {
        name: "NGAGE RHYTHM",
        subTitle: "Innovation Jam",
        category: "NGAGE Rhythm",
        img: innovationJam,
        duration: "3 days",
        price: "US$1,499",
        season: "Year-round",
        theme: "Fun, Teamwork",
        outcome: "Idea generation",
        description: "Employees submit ideas, vote, and respond to creative prompts. The experience encourages participation and shared ownership of ideas.",
        howToWin: "Top 3 most innovative persons win. Bonus for the person with the most votes.",
        activities: ["Social Quest", "Survey ", "Mini-Quest", "Picture Puzzle"],
        prizes: "Included"
    },
]